"""empty message

Revision ID: b1fabe68e713
Revises: 
Create Date: 2019-12-15 19:42:28.231748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1fabe68e713'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('abilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('thumbnail_alt_text', sa.String(), nullable=True),
    sa.Column('weakness', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('collectibles_slug', sa.String(), nullable=True),
    sa.Column('featured', sa.String(), nullable=True),
    sa.Column('thumbnail_image', sa.String(), nullable=True),
    sa.Column('type', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
